apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: juiceshop
  namespace: juiceshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: juiceshop
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 500Mi
